import { Inter } from 'next/font/google';
import "./globals.css";
import mongodbConnect from '@/backend/lib/mongodb';

import { ThemeProvider } from '@/context/Theme';
import ChangeTheme from '@/components/layouts/ChangeTheme';
import { cookies } from 'next/headers';
import { GlobalProvider } from "./GlobalProvider";

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: "Hand Time Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await mongodbConnect();
  
  // Create a new cookies instance
  const cookieStore = cookies();
  // Get theme from cookie
  const themeCookie = cookieStore.get('theme');
  const initialTheme = themeCookie?.value || 'light';

  return (
    <html lang="en" className={initialTheme === 'dark' ? 'dark' : 'light'}>
      <body className={inter.className}>
        <ThemeProvider initialTheme={initialTheme}>
          <GlobalProvider>
            {children}
            <ChangeTheme />
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}